# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 07:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick_name', models.CharField(max_length=256)),
                ('gender', models.IntegerField(default=0)),
                ('language', models.CharField(max_length=256)),
                ('country', models.CharField(max_length=256)),
                ('province', models.CharField(max_length=256)),
                ('city', models.CharField(max_length=256)),
                ('open_id', models.CharField(max_length=256)),
                ('avatar_url', models.URLField(max_length=256)),
                ('register_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
