//index.js
//获取应用实例
var app = getApp()
var util = require('../../utils/util.js')
Page({
  data: {
    toView: 'A',
    scollTop: 100,
    cityArray: [
      { "type": "A" },
      { "city": "阿坝", "city_en": "Aba", "type": "city" },
      { "city": "阿克苏", "city_en": "Akesu", "type": "city" },
      { "city": "阿拉尔", "city_en": "Alaer", "type": "city" },
      { "city": "阿勒泰", "city_en": "Aletai", "type": "city" },
      { "city": "阿里", "city_en": "Ali", "type": "city" },
      { "city": "安康", "city_en": "Ankang", "type": "city" },
      { "city": "安庆", "city_en": "Anqing", "type": "city" },
      { "city": "鞍山", "city_en": "Anshan", "type": "city" },
      { "city": "安顺", "city_en": "Anshun", "type": "city" },
      { "city": "安阳", "city_en": "Anyang", "type": "city" },
      { "city": "阿图什", "city_en": "Atushi", "type": "city" },
      { "city": "阿左旗", "city_en": "Azuoqi", "type": "city" },
      { "type": "B" },
      { "city": "白城", "city_en": "Baicheng", "type": "city" },
      { "city": "百色", "city_en": "Baise", "type": "city" },
      { "city": "白沙", "city_en": "Baisha", "type": "city" },
      { "city": "白山", "city_en": "Baishan", "type": "city" },
      { "city": "白银", "city_en": "Baiyin", "type": "city" },
      { "city": "保定", "city_en": "Baoding", "type": "city" },
      { "city": "宝鸡", "city_en": "Baoji", "type": "city" },
      { "city": "保山", "city_en": "Baoshan", "type": "city" },
      { "city": "保亭", "city_en": "Baoting", "type": "city" },
      { "city": "包头", "city_en": "Baotou", "type": "city" },
      { "city": "巴中", "city_en": "Bazhong", "type": "city" },
      { "city": "北海", "city_en": "Beihai", "type": "city" },
      { "city": "北京", "city_en": "Beijing", "type": "city" },
      { "city": "蚌埠", "city_en": "Bengbu", "type": "city" },
      { "city": "本溪", "city_en": "Benxi", "type": "city" },
      { "city": "毕节", "city_en": "Bijie", "type": "city" },
      { "city": "滨州", "city_en": "Binzhou", "type": "city" },
      { "city": "博乐", "city_en": "Bole", "type": "city" },
      { "city": "亳州", "city_en": "Bozhou", "type": "city" },
      { "type": "C" },
      { "city": "沧州", "city_en": "Cangzhou", "type": "city" },
      { "city": "长春", "city_en": "Changchun", "type": "city" },
      { "city": "常德", "city_en": "Changde", "type": "city" },
      { "city": "昌都", "city_en": "Changdu", "type": "city" },
      { "city": "昌吉", "city_en": "Changji", "type": "city" },
      { "city": "昌江", "city_en": "Changjiang", "type": "city" },
      { "city": "长沙", "city_en": "Changsha", "type": "city" },
      { "city": "长治", "city_en": "Changzhi", "type": "city" },
      { "city": "常州", "city_en": "Changzhou", "type": "city" },
      { "city": "朝阳", "city_en": "Chaoyang", "type": "city" },
      { "city": "潮州", "city_en": "Chaozhou", "type": "city" },
      { "city": "承德", "city_en": "Chengde", "type": "city" },
      { "city": "成都", "city_en": "Chengdu", "type": "city" },
      { "city": "澄迈", "city_en": "Chengmai", "type": "city" },
      { "city": "郴州", "city_en": "Chenzhou", "type": "city" },
      { "city": "赤峰", "city_en": "Chifeng", "type": "city" },
      { "city": "池州", "city_en": "Chizhou", "type": "city" },
      { "city": "重庆", "city_en": "Chongqing", "type": "city" },
      { "city": "崇左", "city_en": "Chongzuo", "type": "city" },
      { "city": "楚雄", "city_en": "Chuxiong", "type": "city" },
      { "city": "滁州", "city_en": "Chuzhou", "type": "city" },
      { "type": "D" },
      { "city": "大理", "city_en": "Dali", "type": "city" },
      { "city": "大连", "city_en": "Dalian", "type": "city" },
      { "city": "丹东", "city_en": "Dandong", "type": "city" },
      { "city": "儋州", "city_en": "Danzhou", "type": "city" },
      { "city": "大庆", "city_en": "Daqing", "type": "city" },
      { "city": "大同", "city_en": "Datong", "type": "city" },
      { "city": "大兴安岭", "city_en": "Daxinganling", "type": "city" },
      { "city": "达州", "city_en": "Dazhou", "type": "city" },
      { "city": "德宏", "city_en": "Dehong", "type": "city" },
      { "city": "德阳", "city_en": "Deyang", "type": "city" },
      { "city": "德州", "city_en": "Dezhou", "type": "city" },
      { "city": "定安", "city_en": "Dingan", "type": "city" },
      { "city": "定西", "city_en": "Dingxi", "type": "city" },
      { "city": "东方", "city_en": "Dongfang", "type": "city" },
      { "city": "东莞", "city_en": "Dongguan", "type": "city" },
      { "city": "东营", "city_en": "Dongying", "type": "city" },
      { "city": "都匀", "city_en": "Duyun", "type": "city" },
      { "type": "E" },
      { "city": "鄂尔多斯", "city_en": "Eerduosi", "type": "city" },
      { "city": "恩施", "city_en": "Enshi", "type": "city" },
      { "city": "鄂州", "city_en": "Ezhou", "type": "city" },
      { "type": "F" },
      { "city": "防城港", "city_en": "Fangchenggang", "type": "city" },
      { "city": "佛山", "city_en": "Foshan", "type": "city" },
      { "city": "抚顺", "city_en": "Fushun", "type": "city" },
      { "city": "阜新", "city_en": "Fuxin", "type": "city" },
      { "city": "阜阳", "city_en": "Fuyang", "type": "city" },
      { "city": "抚州", "city_en": "Fuzhou", "type": "city" },
      { "city": "福州", "city_en": "Fuzhou", "type": "city" },
      { "type": "G" },
      { "city": "赣州", "city_en": "Ganzhou", "type": "city" },
      { "city": "甘孜", "city_en": "Ganzi", "type": "city" },
      { "city": "格尔木", "city_en": "Geermu", "type": "city" },
      { "city": "广安", "city_en": "Guangan", "type": "city" },
      { "city": "广元", "city_en": "Guangyuan", "type": "city" },
      { "city": "广州", "city_en": "Guangzhou", "type": "city" },
      { "city": "贵港", "city_en": "Guigang", "type": "city" },
      { "city": "桂林", "city_en": "Guilin", "type": "city" },
      { "city": "贵阳", "city_en": "Guiyang", "type": "city" },
      { "city": "果洛", "city_en": "Guoluo", "type": "city" },
      { "city": "固原", "city_en": "Guyuan", "type": "city" },
      { "type": "H" },
      { "city": "哈尔滨", "city_en": "Haerbin", "type": "city" },
      { "city": "海北", "city_en": "Haibei", "type": "city" },
      { "city": "海东", "city_en": "Haidong", "type": "city" },
      { "city": "海口", "city_en": "Haikou", "type": "city" },
      { "city": "海拉尔", "city_en": "Hailaer", "type": "city" },
      { "city": "海南", "city_en": "Hainan", "type": "city" },
      { "city": "海西", "city_en": "Haixi", "type": "city" },
      { "city": "哈密", "city_en": "Hami", "type": "city" },
      { "city": "邯郸", "city_en": "Handan", "type": "city" },
      { "city": "杭州", "city_en": "Hangzhou", "type": "city" },
      { "city": "汉中", "city_en": "Hanzhong", "type": "city" },
      { "city": "鹤壁", "city_en": "Hebi", "type": "city" },
      { "city": "河池", "city_en": "Hechi", "type": "city" },
      { "city": "合肥", "city_en": "Hefei", "type": "city" },
      { "city": "鹤岗", "city_en": "Hegang", "type": "city" },
      { "city": "黑河", "city_en": "Heihe", "type": "city" },
      { "city": "衡水", "city_en": "Hengshui", "type": "city" },
      { "city": "衡阳", "city_en": "Hengyang", "type": "city" },
      { "city": "和田", "city_en": "Hetian", "type": "city" },
      { "city": "河源", "city_en": "Heyuan", "type": "city" },
      { "city": "菏泽", "city_en": "Heze", "type": "city" },
      { "city": "贺州", "city_en": "Hezhou", "type": "city" },
      { "city": "合作", "city_en": "Hezuo", "type": "city" },
      { "city": "红河", "city_en": "Honghe", "type": "city" },
      { "city": "淮安", "city_en": "Huaian", "type": "city" },
      { "city": "淮北", "city_en": "Huaibei", "type": "city" },
      { "city": "怀化", "city_en": "Huaihua", "type": "city" },
      { "city": "淮南", "city_en": "Huainan", "type": "city" },
      { "city": "黄冈", "city_en": "Huanggang", "type": "city" },
      { "city": "黄南", "city_en": "Huangnan", "type": "city" },
      { "city": "黄山", "city_en": "Huangshan", "type": "city" },
      { "city": "黄石", "city_en": "Huangshi", "type": "city" },
      { "city": "呼和浩特", "city_en": "Huhehaote", "type": "city" },
      { "city": "惠州", "city_en": "Huizhou", "type": "city" },
      { "city": "葫芦岛", "city_en": "Huludao", "type": "city" },
      { "city": "湖州", "city_en": "Huzhou", "type": "city" },
      { "type": "J" },
      { "city": "佳木斯", "city_en": "Jiamusi", "type": "city" },
      { "city": "吉安", "city_en": "Jian", "type": "city" },
      { "city": "江门", "city_en": "Jiangmen", "type": "city" },
      { "city": "焦作", "city_en": "Jiaozuo", "type": "city" },
      { "city": "嘉兴", "city_en": "Jiaxing", "type": "city" },
      { "city": "嘉峪关", "city_en": "Jiayuguan", "type": "city" },
      { "city": "揭阳", "city_en": "Jieyang", "type": "city" },
      { "city": "吉林", "city_en": "Jilin", "type": "city" },
      { "city": "济南", "city_en": "Jinan", "type": "city" },
      { "city": "金昌", "city_en": "Jinchang", "type": "city" },
      { "city": "晋城", "city_en": "Jincheng", "type": "city" },
      { "city": "景德镇", "city_en": "Jingdezhen", "type": "city" },
      { "city": "景洪", "city_en": "Jinghong", "type": "city" },
      { "city": "荆门", "city_en": "Jingmen", "type": "city" },
      { "city": "荆州", "city_en": "Jingzhou", "type": "city" },
      { "city": "金华", "city_en": "Jinhua", "type": "city" },
      { "city": "济宁", "city_en": "Jining", "type": "city" },
      { "city": "集宁", "city_en": "Jining", "type": "city" },
      { "city": "晋中", "city_en": "Jinzhong", "type": "city" },
      { "city": "锦州", "city_en": "Jinzhou", "type": "city" },
      { "city": "吉首", "city_en": "Jishou", "type": "city" },
      { "city": "九江", "city_en": "Jiujiang", "type": "city" },
      { "city": "酒泉", "city_en": "Jiuquan", "type": "city" },
      { "city": "鸡西", "city_en": "Jixi", "type": "city" },
      { "city": "济源", "city_en": "Jiyuan", "type": "city" },
      { "type": "K" },
      { "city": "开封", "city_en": "Kaifeng", "type": "city" },
      { "city": "凯里", "city_en": "Kaili", "type": "city" },
      { "city": "喀什", "city_en": "Kashi", "type": "city" },
      { "city": "克拉玛依", "city_en": "Kelamayi", "type": "city" },
      { "city": "库尔勒", "city_en": "Kuerle", "type": "city" },
      { "city": "昆明", "city_en": "Kunming", "type": "city" },
      { "type": "L" },
      { "city": "来宾", "city_en": "Laibin", "type": "city" },
      { "city": "莱芜", "city_en": "Laiwu", "type": "city" },
      { "city": "廊坊", "city_en": "Langfang", "type": "city" },
      { "city": "兰州", "city_en": "Lanzhou", "type": "city" },
      { "city": "拉萨", "city_en": "Lasa", "type": "city" },
      { "city": "乐东", "city_en": "Ledong", "type": "city" },
      { "city": "乐山", "city_en": "Leshan", "type": "city" },
      { "city": "凉山", "city_en": "Liangshan", "type": "city" },
      { "city": "连云港", "city_en": "Lianyungang", "type": "city" },
      { "city": "聊城", "city_en": "Liaocheng", "type": "city" },
      { "city": "辽阳", "city_en": "Liaoyang", "type": "city" },
      { "city": "辽源", "city_en": "Liaoyuan", "type": "city" },
      { "city": "丽江", "city_en": "Lijiang", "type": "city" },
      { "city": "临沧", "city_en": "Lincang", "type": "city" },
      { "city": "临汾", "city_en": "Linfen", "type": "city" },
      { "city": "临高", "city_en": "Lingao", "type": "city" },
      { "city": "陵水", "city_en": "Lingshui", "type": "city" },
      { "city": "临河", "city_en": "Linhe", "type": "city" },
      { "city": "临夏", "city_en": "Linxia", "type": "city" },
      { "city": "临沂", "city_en": "Linyi", "type": "city" },
      { "city": "林芝", "city_en": "Linzhi", "type": "city" },
      { "city": "丽水", "city_en": "Lishui", "type": "city" },
      { "city": "柳州", "city_en": "Liuzhou", "type": "city" },
      { "city": "龙岩", "city_en": "Longyan", "type": "city" },
      { "city": "娄底", "city_en": "Loudi", "type": "city" },
      { "city": "六安", "city_en": "Luan", "type": "city" },
      { "city": "漯河", "city_en": "Luohe", "type": "city" },
      { "city": "洛阳", "city_en": "Luoyang", "type": "city" },
      { "city": "泸州", "city_en": "Luzhou", "type": "city" },
      { "city": "吕梁", "city_en": "Lvliang", "type": "city" },
      { "type": "M" },
      { "city": "马鞍山", "city_en": "Maanshan", "type": "city" },
      { "city": "茂名", "city_en": "Maoming", "type": "city" },
      { "city": "眉山", "city_en": "Meishan", "type": "city" },
      { "city": "梅州", "city_en": "Meizhou", "type": "city" },
      { "city": "绵阳", "city_en": "Mianyang", "type": "city" },
      { "city": "牡丹江", "city_en": "Mudanjiang", "type": "city" },
      { "type": "N" },
      { "city": "南昌", "city_en": "Nanchang", "type": "city" },
      { "city": "南充", "city_en": "Nanchong", "type": "city" },
      { "city": "南京", "city_en": "Nanjing", "type": "city" },
      { "city": "南宁", "city_en": "Nanning", "type": "city" },
      { "city": "南平", "city_en": "Nanping", "type": "city" },
      { "city": "南沙", "city_en": "Nansha", "type": "city" },
      { "city": "南通", "city_en": "Nantong", "type": "city" },
      { "city": "南阳", "city_en": "Nanyang", "type": "city" },
      { "city": "那曲", "city_en": "Naqu", "type": "city" },
      { "city": "内江", "city_en": "Neijiang", "type": "city" },
      { "city": "宁波", "city_en": "Ningbo", "type": "city" },
      { "city": "宁德", "city_en": "Ningde", "type": "city" },
      { "city": "怒江", "city_en": "Nujiang", "type": "city" },
      { "type": "P" },
      { "city": "盘锦", "city_en": "Panjin", "type": "city" },
      { "city": "攀枝花", "city_en": "Panzhihua", "type": "city" },
      { "city": "平顶山", "city_en": "Pingdingshan", "type": "city" },
      { "city": "平凉", "city_en": "Pingliang", "type": "city" },
      { "city": "萍乡", "city_en": "Pingxiang", "type": "city" },
      { "city": "普洱", "city_en": "Puer", "type": "city" },
      { "city": "莆田", "city_en": "Putian", "type": "city" },
      { "city": "濮阳", "city_en": "Puyang", "type": "city" },
      { "type": "Q" },
      { "city": "潜江", "city_en": "Qianjiang", "type": "city" },
      { "city": "青岛", "city_en": "Qingdao", "type": "city" },
      { "city": "庆阳", "city_en": "Qingyang", "type": "city" },
      { "city": "清远", "city_en": "Qingyuan", "type": "city" },
      { "city": "秦皇岛", "city_en": "Qinhuangdao", "type": "city" },
      { "city": "钦州", "city_en": "Qinzhou", "type": "city" },
      { "city": "琼海", "city_en": "Qionghai", "type": "city" },
      { "city": "琼中", "city_en": "Qiongzhong", "type": "city" },
      { "city": "齐齐哈尔", "city_en": "Qiqihaer", "type": "city" },
      { "city": "七台河", "city_en": "Qitaihe", "type": "city" },
      { "city": "泉州", "city_en": "Quanzhou", "type": "city" },
      { "city": "曲靖", "city_en": "Qujing", "type": "city" },
      { "city": "衢州", "city_en": "Quzhou", "type": "city" },
      { "type": "R" },
      { "city": "日喀则", "city_en": "Rikaze", "type": "city" },
      { "city": "日照", "city_en": "Rizhao", "type": "city" },
      { "type": "S" },
      { "city": "三门峡", "city_en": "Sanmenxia", "type": "city" },
      { "city": "三明", "city_en": "Sanming", "type": "city" },
      { "city": "三亚", "city_en": "Sanya", "type": "city" },
      { "city": "上海", "city_en": "Shanghai", "type": "city" },
      { "city": "商洛", "city_en": "Shangluo", "type": "city" },
      { "city": "商丘", "city_en": "Shangqiu", "type": "city" },
      { "city": "上饶", "city_en": "Shangrao", "type": "city" },
      { "city": "山南", "city_en": "Shannan", "type": "city" },
      { "city": "汕头", "city_en": "Shantou", "type": "city" },
      { "city": "汕尾", "city_en": "Shanwei", "type": "city" },
      { "city": "韶关", "city_en": "Shaoguan", "type": "city" },
      { "city": "绍兴", "city_en": "Shaoxing", "type": "city" },
      { "city": "邵阳", "city_en": "Shaoyang", "type": "city" },
      { "city": "神农架", "city_en": "Shennongjia", "type": "city" },
      { "city": "沈阳", "city_en": "Shenyang", "type": "city" },
      { "city": "深圳", "city_en": "Shenzhen", "type": "city" },
      { "city": "石河子", "city_en": "Shihezi", "type": "city" },
      { "city": "石家庄", "city_en": "Shijiazhuang", "type": "city" },
      { "city": "十堰", "city_en": "Shiyan", "type": "city" },
      { "city": "石嘴山", "city_en": "Shizuishan", "type": "city" },
      { "city": "双鸭山", "city_en": "Shuangyashan", "type": "city" },
      { "city": "水城", "city_en": "Shuicheng", "type": "city" },
      { "city": "朔州", "city_en": "Shuozhou", "type": "city" },
      { "city": "四平", "city_en": "Siping", "type": "city" },
      { "city": "松原", "city_en": "Songyuan", "type": "city" },
      { "city": "绥化", "city_en": "Suihua", "type": "city" },
      { "city": "遂宁", "city_en": "Suining", "type": "city" },
      { "city": "随州", "city_en": "Suizhou", "type": "city" },
      { "city": "宿迁", "city_en": "Suqian", "type": "city" },
      { "city": "宿州", "city_en": "Suzhou", "type": "city" },
      { "city": "苏州", "city_en": "Suzhou", "type": "city" },
      { "type": "T" },
      { "city": "塔城", "city_en": "Tacheng", "type": "city" },
      { "city": "泰安", "city_en": "Taian", "type": "city" },
      { "city": "太原", "city_en": "Taiyuan", "type": "city" },
      { "city": "台州", "city_en": "Taizhou", "type": "city" },
      { "city": "泰州", "city_en": "Taizhou", "type": "city" },
      { "city": "唐山", "city_en": "Tangshan", "type": "city" },
      { "city": "天津", "city_en": "Tianjin", "type": "city" },
      { "city": "天门", "city_en": "Tianmen", "type": "city" },
      { "city": "天水", "city_en": "Tianshui", "type": "city" },
      { "city": "铁岭", "city_en": "Tieling", "type": "city" },
      { "city": "铜川", "city_en": "Tongchuan", "type": "city" },
      { "city": "通化", "city_en": "Tonghua", "type": "city" },
      { "city": "通辽", "city_en": "Tongliao", "type": "city" },
      { "city": "铜陵", "city_en": "Tongling", "type": "city" },
      { "city": "铜仁", "city_en": "Tongren", "type": "city" },
      { "city": "吐鲁番", "city_en": "Tulufan", "type": "city" },
      { "city": "屯昌", "city_en": "Tunchang", "type": "city" },
      { "type": "W" },
      { "city": "万宁", "city_en": "Wanning", "type": "city" },
      { "city": "潍坊", "city_en": "Weifang", "type": "city" },
      { "city": "威海", "city_en": "Weihai", "type": "city" },
      { "city": "渭南", "city_en": "Weinan", "type": "city" },
      { "city": "文昌", "city_en": "Wenchang", "type": "city" },
      { "city": "文山", "city_en": "Wenshan", "type": "city" },
      { "city": "温州", "city_en": "Wenzhou", "type": "city" },
      { "city": "武都", "city_en": "Wudu", "type": "city" },
      { "city": "乌海", "city_en": "Wuhai", "type": "city" },
      { "city": "武汉", "city_en": "Wuhan", "type": "city" },
      { "city": "芜湖", "city_en": "Wuhu", "type": "city" },
      { "city": "五家渠", "city_en": "Wujiaqu", "type": "city" },
      { "city": "乌兰浩特", "city_en": "Wulanhaote", "type": "city" },
      { "city": "乌鲁木齐", "city_en": "Wulumuqi", "type": "city" },
      { "city": "武威", "city_en": "Wuwei", "type": "city" },
      { "city": "无锡", "city_en": "Wuxi", "type": "city" },
      { "city": "五指山", "city_en": "Wuzhishan", "type": "city" },
      { "city": "中沙", "city_en": "Wuzhishan", "type": "city" },
      { "city": "吴忠", "city_en": "Wuzhong", "type": "city" },
      { "city": "梧州", "city_en": "Wuzhou", "type": "city" },
      { "type": "X" },
      { "city": "厦门", "city_en": "Xiamen", "type": "city" },
      { "city": "西安", "city_en": "Xian", "type": "city" },
      { "city": "香格里拉", "city_en": "Xianggelila", "type": "city" },
      { "city": "湘潭", "city_en": "Xiangtan", "type": "city" },
      { "city": "襄阳", "city_en": "Xiangyang", "type": "city" },
      { "city": "咸宁", "city_en": "Xianning", "type": "city" },
      { "city": "仙桃", "city_en": "Xiantao", "type": "city" },
      { "city": "咸阳", "city_en": "Xianyang", "type": "city" },
      { "city": "孝感", "city_en": "Xiaogan", "type": "city" },
      { "city": "锡林浩特", "city_en": "Xilinhaote", "type": "city" },
      { "city": "邢台", "city_en": "Xingtai", "type": "city" },
      { "city": "兴义", "city_en": "Xingyi", "type": "city" },
      { "city": "西宁", "city_en": "Xining", "type": "city" },
      { "city": "新乡", "city_en": "Xinxiang", "type": "city" },
      { "city": "信阳", "city_en": "Xinyang", "type": "city" },
      { "city": "新余", "city_en": "Xinyu", "type": "city" },
      { "city": "忻州", "city_en": "Xinzhou", "type": "city" },
      { "city": "西沙", "city_en": "Xisha", "type": "city" },
      { "city": "宣城", "city_en": "Xuancheng", "type": "city" },
      { "city": "许昌", "city_en": "Xuchang", "type": "city" },
      { "city": "徐州", "city_en": "Xuzhou", "type": "city" },
      { "type": "Y" },
      { "city": "雅安", "city_en": "Yaan", "type": "city" },
      { "city": "延安", "city_en": "Yanan", "type": "city" },
      { "city": "盐城", "city_en": "Yancheng", "type": "city" },
      { "city": "阳江", "city_en": "Yangjiang", "type": "city" },
      { "city": "杨凌", "city_en": "Yangling", "type": "city" },
      { "city": "阳泉", "city_en": "Yangquan", "type": "city" },
      { "city": "扬州", "city_en": "Yangzhou", "type": "city" },
      { "city": "延吉", "city_en": "Yanji", "type": "city" },
      { "city": "烟台", "city_en": "Yantai", "type": "city" },
      { "city": "宜宾", "city_en": "Yibin", "type": "city" },
      { "city": "宜昌", "city_en": "Yichang", "type": "city" },
      { "city": "宜春", "city_en": "Yichun", "type": "city" },
      { "city": "伊春", "city_en": "Yichun", "type": "city" },
      { "city": "银川", "city_en": "Yinchuan", "type": "city" },
      { "city": "营口", "city_en": "Yingkou", "type": "city" },
      { "city": "鹰潭", "city_en": "Yingtan", "type": "city" },
      { "city": "伊宁", "city_en": "Yining", "type": "city" },
      { "city": "益阳", "city_en": "Yiyang", "type": "city" },
      { "city": "永州", "city_en": "Yongzhou", "type": "city" },
      { "city": "岳阳", "city_en": "Yueyang", "type": "city" },
      { "city": "玉林", "city_en": "Yulin", "type": "city" },
      { "city": "榆林", "city_en": "Yulin", "type": "city" },
      { "city": "运城", "city_en": "Yuncheng", "type": "city" },
      { "city": "云浮", "city_en": "Yunfu", "type": "city" },
      { "city": "玉树", "city_en": "Yushu", "type": "city" },
      { "city": "玉溪", "city_en": "Yuxi", "type": "city" },
      { "type": "Z" },
      { "city": "枣庄", "city_en": "Zaozhuang", "type": "city" },
      { "city": "张家界", "city_en": "Zhangjiajie", "type": "city" },
      { "city": "张家口", "city_en": "Zhangjiakou", "type": "city" },
      { "city": "张掖", "city_en": "Zhangye", "type": "city" },
      { "city": "漳州", "city_en": "Zhangzhou", "type": "city" },
      { "city": "湛江", "city_en": "Zhanjiang", "type": "city" },
      { "city": "肇庆", "city_en": "Zhaoqing", "type": "city" },
      { "city": "昭通", "city_en": "Zhaotong", "type": "city" },
      { "city": "郑州", "city_en": "Zhengzhou", "type": "city" },
      { "city": "镇江", "city_en": "Zhenjiang", "type": "city" },
      { "city": "中山", "city_en": "Zhongshan", "type": "city" },
      { "city": "中卫", "city_en": "Zhongwei", "type": "city" },
      { "city": "周口", "city_en": "Zhoukou", "type": "city" },
      { "city": "舟山", "city_en": "Zhoushan", "type": "city" },
      { "city": "珠海", "city_en": "Zhuhai", "type": "city" },
      { "city": "驻马店", "city_en": "Zhumadian", "type": "city" },
      { "city": "株洲", "city_en": "Zhuzhou", "type": "city" },
      { "city": "淄博", "city_en": "Zibo", "type": "city" },
      { "city": "自贡", "city_en": "Zigong", "type": "city" },
      { "city": "资阳", "city_en": "Ziyang", "type": "city" },
      { "city": "遵义", "city_en": "Zunyi", "type": "city" },

    ],
    letterArray: ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z']

  },

  indexEvent: function (e) {
    //console.log(e);

    let offsetTop = e.changedTouches["0"].pageY;
    let letterIndex = (offsetTop - 20) / 15;
    let letter = this.data.letterArray[letterIndex - 1];
    //console.log(letter);
    //console.log(e.changedTouches["0"].pageY);


    this.setData({ toView: letter })
    //通过flex设置listview和sidebar按column排列
    //设置sidebar的height固定为为50px，设置sidebar中的view固定height为为20px
    //获得当前手指触摸距离屏幕顶部的位置，减去50px，再除以20,用获得的值根据a-z的array[index]，获得字母，通过字母设置toview

  },
  tapEvent: function (e) {
    //console.log(e);
    this.setData({ toView: e.currentTarget.id.trim() });
  },
  onLoad: function () {
    //判断缓存时间
    var cityData = util.getCity();
    var that = this;
    that.setData({
      cityData: cityData
    })
  },
  cityClickEvent: function (e) {

    let res = wx.getStorageSync('myCity')
    let city = e.currentTarget.id.trim();



    //如果mycity中有内容
    if (res) {
      //如果mycity已经超过了了5个，则提示
      if (res.length >= 5) {
        wx.showToast({
          title: '添加失败，最多关注5个城市！',
          icon: 'fail',
          duration: 2000
        })
        return;
      }

      //如果包含
      if (util.contains(res, city)) {
        wx.showToast({
          title: '城市已经存在！',
          icon: 'fail',
          duration: 2000
        })

      } else {
        //如果不包含
        res.push(city);
        this.saveCity(res);
      }
    } else {
      res = [city];
      this.saveCity(res);
    }




  },
  saveCity: function (city) {
    wx.setStorage({
      key: 'myCity',
      data: city,
      success: function (res) {
        wx.showToast({
          title: '添加城市成功',
          icon: 'success',
          duration: 2000
        })
      },
      fail: function () {
        // fail
      },
      complete: function () {
        // complete
      }
    })
  }
})
