# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='client_mark',
            field=models.CharField(blank=True, default='weixin', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='weixin_avatarUrl',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='weixin_nickName',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
