<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/6/15
 * Time: 11:01
 */

namespace app\models\common\admin\validator;

use app\modules\mch\models\LevelListForm;
use yii\validators\Validator;

class AttrValidator extends Validator
{
    public $min = 0;
    public $max = 999999;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function validateAttribute($model, $attribute)
    {
        $levelListForm = new LevelListForm();
        $levelList = $levelListForm->getAllLevel();

        $attrs = is_string($model->attr) ? \Yii::$app->serializer->decode($model->attr) : $model->attr;
        if ($attrs) {
            foreach ($attrs as $value) {
                if (floatval($value['price']) < $this->min) {
                    $model->addError($attribute, '规格价格必须不小于0');
                } elseif (floatval($value['price']) > $this->max) {
                    $model->addError($attribute, '规格价格必须不大于999999');
                }
                if (floatval($value['num']) < $this->min) {
                    $model->addError($attribute, '规格库存必须不小于0');
                } elseif (floatval($value['num']) > $this->max) {
                    $model->addError($attribute, '规格库存必须不大于999999');
                }

                $f = floatval($value['share_commission_first']);
                $s = floatval($value['share_commission_second']);
                $t = floatval($value['share_commission_third']);
                // 多规格分销价判断
                if ($f < $this->min || $s < $this->min || $t < $this->min) {
                    $model->addError($attribute, '分销价必须不小于0');
                } else if ($f > $this->max || $s > $this->max || $t > $this->max) {
                    $model->addError($attribute, '分销价必须不大于999999');
                }

                // 多规格会员价判断
                foreach ($levelList as $level) {
                    $keyName = 'member' . $level['level'];
                    if (floatval($value[$keyName]) < $this->min) {
                        $model->addError($attribute, '会员价必须不小于0');
                    } elseif (floatval($value[$keyName]) > $this->max) {
                        $model->addError($attribute, '会员价必须不大于999999');
                    }
                }
            }
        }

        //单规格会员价
        foreach ($model['attr_member_price_List'] as $item) {
            if ($item < $this->min) {
                $model->addError($attribute, '会员价必须不小于0');
            } elseif ($item > $this->max) {
                $model->addError($attribute, '会员价必须不大于999999');
            }
        }
    }
}
