<?php
/**
 * Created by PhpStorm.
 * User: peize
 * Date: 2017/11/22
 * Time: 14:55
 */

namespace app\modules\mch\controllers\group;

class Controller extends \app\modules\mch\controllers\Controller
{
//    public function render($view, $params = [])
//    {
//        $params['is_group'] = 1;
//        return parent::render($view, $params); // TODO: Change the autogenerated stub
//    }
}
