/**
 * Created by Administrator on 2017/3/16.
 */
module.exports={

    name:'环银电影城(世贸广场店)',
    code:'k1045',
    pol:[15,68],
    adress:'江汉区解放大道686号世贸广场8楼',


        movies:
    [
    {
        title:'金刚狼3:殊死一战',
        id:1,
        rating:8.8,
        jiamjie:'101分钟|动作|休.杰克曼',
        cover:'http://localhost:8888/public/img/movie-cover/4.png',
        sessions:[
            [
                {start:'11:00',
                    end:'12:59',
                    effects:'英语3D',
                    room:'9号厅(大)',
                    price:35,
                    discount:26},
                {start:'11:20',
                    end:'13:19',
                    effects:'英语3D',
                    room:'3号厅-4DX',
                    price:48,
                    discount:39}

            ],
            [    {start:'10:20',
                end:'12:19',
                effects:'英语IMAX3D',
                room:'1号厅(大)',
                price:43,
                discount:30},
                {start:'10:40',
                    end:'12:39',
                    effects:'英语3D',
                    room:'7号厅',
                    price:35,
                    discount:26},
                {start:'11:00',
                    end:'12:59',
                    effects:'英语3D',
                    room:'9号厅(大)',
                    price:35,
                    discount:26},
                {start:'11:20',
                    end:'13:19',
                    effects:'英语3D',
                    room:'3号厅-4DX',
                    price:48,
                    discount:39}
            ]
            ]
    },
        {
            title:'生化危机:终章',
            id:2,
            rating:7.6,
            jiamjie:'101分钟|动作|米拉.乔沃维奇',
            cover:'http://localhost:8888/public/img/movie-cover/1.png'
            ,
            sessions:[
                [
                    {start:'11:00',
                        end:'12:59',
                        effects:'英语3D',
                        room:'9号厅(大)',
                        price:35,
                        discount:26},
                    {start:'11:20',
                        end:'13:19',
                        effects:'英语3D',
                        room:'3号厅-4DX',
                        price:48,
                        discount:39}

                ],
                [    {start:'10:20',
                    end:'12:19',
                    effects:'英语IMAX3D',
                    room:'1号厅(大)',
                    price:43,
                    discount:30},
                    {start:'10:40',
                        end:'12:39',
                        effects:'英语3D',
                        room:'7号厅',
                        price:35,
                        discount:26},
                    {start:'11:00',
                        end:'12:59',
                        effects:'英语3D',
                        room:'9号厅(大)',
                        price:35,
                        discount:26},
                    {start:'11:20',
                        end:'13:19',
                        effects:'英语3D',
                        room:'3号厅-4DX',
                        price:48,
                        discount:39}
                ]
            ]
        },
        {
            title:'刺客信条',
            id:3,
            rating:6.9,
            jiamjie:'101分钟|动作|迈克尔.法斯宾德',
            cover:'http://localhost:8888/public/img/movie-cover/2.png'
            ,
            sessions:[
                [
                    {start:'11:00',
                        end:'12:59',
                        effects:'英语3D',
                        room:'9号厅(大)',
                        price:35,
                        discount:26},
                    {start:'11:20',
                        end:'13:19',
                        effects:'英语3D',
                        room:'3号厅-4DX',
                        price:48,
                        discount:39}

                ],
                [    {start:'10:20',
                    end:'12:19',
                    effects:'英语IMAX3D',
                    room:'1号厅(大)',
                    price:43,
                    discount:30},
                    {start:'10:40',
                        end:'12:39',
                        effects:'英语3D',
                        room:'7号厅',
                        price:35,
                        discount:26},
                    {start:'11:00',
                        end:'12:59',
                        effects:'英语3D',
                        room:'9号厅(大)',
                        price:35,
                        discount:26},
                    {start:'11:20',
                        end:'13:19',
                        effects:'英语3D',
                        room:'3号厅-4DX',
                        price:48,
                        discount:39}
                ]
            ]
        },
        {
            title:'爱乐之城',
            id:4,
            rating:9.1,
            jiamjie:'101分钟|动作|爱玛.斯通',
            cover:'http://localhost:8888/public/img/movie-cover/3.png'
            ,
            sessions:[
                [
                    {start:'11:00',
                        end:'12:59',
                        effects:'英语3D',
                        room:'9号厅(大)',
                        price:35,
                        discount:26},
                    {start:'11:20',
                        end:'13:19',
                        effects:'英语3D',
                        room:'3号厅-4DX',
                        price:48,
                        discount:39}

                ],
                [    {start:'10:20',
                    end:'12:19',
                    effects:'英语IMAX3D',
                    room:'1号厅(大)',
                    price:43,
                    discount:30},
                    {start:'10:40',
                        end:'12:39',
                        effects:'英语3D',
                        room:'7号厅',
                        price:35,
                        discount:26},
                    {start:'11:00',
                        end:'12:59',
                        effects:'英语3D',
                        room:'9号厅(大)',
                        price:35,
                        discount:26},
                    {start:'11:20',
                        end:'13:19',
                        effects:'英语3D',
                        room:'3号厅-4DX',
                        price:48,
                        discount:39}
                ]
            ]
        },
        {
            title:'欢乐好声音',
            id:5,
            rating:6.7,
            jiamjie:'101分钟|动作|马修.麦康纳',
            cover:'http://localhost:8888/public/img/movie-cover/4.png'
            ,
            sessions:[
                [
                    {start:'11:00',
                        end:'12:59',
                        effects:'英语3D',
                        room:'9号厅(大)',
                        price:35,
                        discount:26},
                    {start:'11:20',
                        end:'13:19',
                        effects:'英语3D',
                        room:'3号厅-4DX',
                        price:48,
                        discount:39}

                ],
                [    {start:'10:20',
                    end:'12:19',
                    effects:'英语IMAX3D',
                    room:'1号厅(大)',
                    price:43,
                    discount:30},
                    {start:'10:40',
                        end:'12:39',
                        effects:'英语3D',
                        room:'7号厅',
                        price:35,
                        discount:26},
                    {start:'11:00',
                        end:'12:59',
                        effects:'英语3D',
                        room:'9号厅(大)',
                        price:35,
                        discount:26},
                    {start:'11:20',
                        end:'13:19',
                        effects:'英语3D',
                        room:'3号厅-4DX',
                        price:48,
                        discount:39}
                ]
            ]
        }
    ]

}

