<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/6/15
 * Time: 11:01
 */

namespace app\modules\mch\models;

use yii\validators\NumberValidator;
use yii\validators\Validator;

class AttrValidator extends Validator
{
    public $min = 0;
    public $max = 999999;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function validateAttribute($model, $attribute)
    {
        foreach ($model->attr as $value) {
            if (floatval($value['price']) < $this->min) {
                $model->addError($attribute, '规格价格必须不小于0');
            } elseif (floatval($value['price']) > $this->max) {
                $model->addError($attribute, '规格价格必须不大于999999');
            }
            if (floatval($value['num']) < $this->min) {
                $model->addError($attribute, '规格库存必须不小于0');
            } elseif (floatval($value['num']) > $this->max) {
                $model->addError($attribute, '规格库存必须不大于999999');
            }
        }
    }
}
