module.exports=[
    {
        title:'果蔬花卉',
        src:'/image/customer/index/4cai.png',
        srcH:'/image/customer/index/4caih.png'
    },
    {
        title:'商店超市',
        src:'/image/customer/index/5cai.png',
        srcH:'/image/customer/index/5caih.png'
    },
    {
        title:'美食营养',
         src:'/image/customer/index/6cai.png',
        srcH:'/image/customer/index/6caih.png'
    },
    {
        title:'生活服务',
         src:'/image/customer/index/7cai.png',
        srcH:'/image/customer/index/7caih.png'
    },
    {
        title:'家政服务',
        src:'/image/customer/index/8cai.png',
        srcH:'/image/customer/index/8caih.png'
    },
    {
        title:'展销展示',
         src:'/image/customer/index/9cai.png',
        srcH:'/image/customer/index/9caih.png'
    },
    {
        title:'社区服务',
         src:'/image/customer/index/10cai.png',
        srcH:'/image/customer/index/10caih.png'
    },
    {
        title:'其他服务',
         src:'/image/customer/index/11cai.png',
        srcH:'/image/customer/index/11caih.png'
    }
]