# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 10:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_message', models.CharField(blank=True, default='', max_length=140, null=True)),
                ('comment_user_name', models.CharField(blank=True, default='', max_length=70, null=True)),
                ('comment_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=70)),
                ('name', models.CharField(max_length=70)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('download_speed', models.CharField(blank=True, max_length=70, null=True)),
                ('speed_test_link', models.CharField(blank=True, max_length=100, null=True)),
                ('price_indication', models.CharField(blank=True, default='', max_length=70, null=True)),
                ('bathroom', models.BooleanField(default=False)),
                ('commit_user_name', models.CharField(blank=True, default='', max_length=70, null=True)),
                ('commit_message', models.CharField(blank=True, max_length=140, null=True)),
                ('commit_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
