# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 10:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coffee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spot',
            name='commit_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='spot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffee.Spot'),
        ),
    ]
