# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0003_auto_20170401_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_mark',
            field=models.CharField(blank=True, default='comment', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='spot',
            name='speed_test_link',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
    ]
