# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0004_auto_20170401_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_user_avatarurl',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='spot',
            name='upload_speed',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
